[mgr]
show_hidden = true
ratio = [ 2, 3, 4 ]

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[opener]
edit = [
  { run = 'nvim "$@"', block = true },
]

[[plugin.prepend_previewers]]
url = "*/"
run = "eza-preview"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
