import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { isAbsolute, join, relative, resolve } from "node:path";
import type { BuildSystemPromptOptions, ExtensionAPI } from "@earendil-works/pi-coding-agent";

type SkillProfile = {
	skills?: unknown;
};

type GlobalConfig = {
	skillProfiles?: Record<string, SkillProfile>;
};

type ProjectConfig = {
	/** Preferred form: an array allows several profiles to be combined. */
	skillProfiles?: unknown;
	/** Backward/convenience form for a single profile. */
	skillProfile?: unknown;
};

const DEFAULT_SKILL_PROFILE_NAME = "_default";

type SkillLike = {
	name: string;
	description: string;
	filePath: string;
	disableModelInvocation?: boolean;
};

const GLOBAL_SKILL_ROOTS = [
	join(homedir(), ".pi", "agent", "skills"),
	join(homedir(), ".agents", "skills"),
].map((path) => resolve(path));

function readJsonFile<T>(path: string): T | undefined {
	if (!existsSync(path)) return undefined;

	try {
		return JSON.parse(readFileSync(path, "utf8")) as T;
	} catch {
		// A malformed optional configuration must not prevent Pi from starting.
		return undefined;
	}
}

function asStrings(value: unknown): string[] {
	if (typeof value === "string") return [value];
	if (!Array.isArray(value)) return [];
	return value.filter((item): item is string => typeof item === "string");
}

function readEnabledProfiles(cwd: string): string[] {
	const projectConfig = readJsonFile<ProjectConfig>(join(cwd, ".pi", "settings.json"));
	const projectProfiles = asStrings(projectConfig?.skillProfiles ?? projectConfig?.skillProfile);

	// Always use the default profile as the baseline set of globally visible skills.
	return Array.from(new Set([DEFAULT_SKILL_PROFILE_NAME, ...projectProfiles]));
}

function readAllowedSkills(profileNames: string[]): Set<string> | undefined {
	if (profileNames.length === 0) return undefined;

	const config = readJsonFile<GlobalConfig>(join(homedir(), ".pi", "agent", "settings.json"));
	if (!config?.skillProfiles || typeof config.skillProfiles !== "object") return new Set();

	const allowed = new Set<string>();
	for (const profileName of profileNames) {
		const profile = config.skillProfiles[profileName];
		if (!profile || typeof profile !== "object") continue;
		for (const skillName of asStrings(profile.skills)) allowed.add(skillName);
	}
	return allowed;
}

function formatProfileSkillSummary(profileNames: string[], allowedSkills: Set<string>): string | undefined {
	if (profileNames.length === 0) return undefined;

	const skillNames = Array.from(allowedSkills).sort((a, b) => a.localeCompare(b));
	return [
		"[Skill Profiles]",
		`Profiles: ${profileNames.join(", ")}`,
		skillNames.length === 0 ? "Skills: (none)" : `Skills: ${skillNames.join(", ")}`,
	].join("\n");
}

function isUnder(path: string, root: string): boolean {
	const rel = relative(root, resolve(path));
	return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function isGlobalSkill(skill: SkillLike): boolean {
	return GLOBAL_SKILL_ROOTS.some((root) => isUnder(skill.filePath, root));
}

function escapeXml(value: string): string {
	return value
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&apos;");
}

function renderSkillEntries(skills: SkillLike[]): string {
	return skills
		.map(
			(skill) =>
				[
					"  <skill>",
					`    <name>${escapeXml(skill.name)}</name>`,
					`    <description>${escapeXml(skill.description)}</description>`,
					`    <location>${escapeXml(skill.filePath)}</location>`,
					"  </skill>",
				].join("\n"),
		)
		.join("\n");
}

/**
 * Filters the skills section generated by Pi. This intentionally changes only
 * the prompt sent to the model; Pi's own skill registry remains untouched.
 */
export function filterSkillsInSystemPrompt(
	systemPrompt: string,
	options: BuildSystemPromptOptions,
	allowedGlobalSkills: Set<string>,
	explicitSkills: Set<string> = new Set(),
): string {
	const sectionStart = systemPrompt.indexOf("<available_skills>");
	const sectionEndMarker = "</available_skills>";
	if (sectionStart < 0) return systemPrompt;

	const sectionEnd = systemPrompt.indexOf(sectionEndMarker, sectionStart);
	if (sectionEnd < 0) return systemPrompt;

	const skills = (options.skills ?? []) as SkillLike[];
	const visibleSkills = skills.filter((skill) => {
		// Preserve Pi's per-skill opt-out unless the user explicitly invoked it.
		if (skill.disableModelInvocation && !explicitSkills.has(skill.name)) return false;
		return !isGlobalSkill(skill) || allowedGlobalSkills.has(skill.name) || explicitSkills.has(skill.name);
	});

	const replacement =
		visibleSkills.length === 0
			? ""
			: `<available_skills>\n${renderSkillEntries(visibleSkills)}\n${sectionEndMarker}`;

	// The explanatory text immediately before the XML block is part of Pi's
	// skills prompt. Remove it too when no skill remains visible.
	let replacementStart = sectionStart;
	if (visibleSkills.length === 0) {
		const intro = "The following skills provide specialized instructions for specific tasks.";
		const introStart = systemPrompt.lastIndexOf(intro, sectionStart);
		if (introStart >= 0) {
			replacementStart = introStart;
			if (replacementStart > 0 && systemPrompt[replacementStart - 1] === "\n") replacementStart--;
		}
	}

	return systemPrompt.slice(0, replacementStart) + replacement + systemPrompt.slice(sectionEnd + sectionEndMarker.length);
}

function findExplicitSkillNames(text: string): Set<string> {
	const names = new Set<string>();
	const pattern = /(?:^|\s)\/skill:([a-z0-9]+(?:-[a-z0-9]+)*)/gi;
	for (const match of text.matchAll(pattern)) names.add(match[1]);
	return names;
}

export default function skillProfiles(pi: ExtensionAPI) {
	let explicitSkillsForNextPrompt = new Set<string>();

	pi.on("session_start", (event, ctx) => {
		if (event.reason !== "startup" || !ctx.hasUI) return;

		const profileNames = readEnabledProfiles(ctx.cwd);
		const allowedGlobalSkills = readAllowedSkills(profileNames) ?? new Set<string>();
		const summary = formatProfileSkillSummary(profileNames, allowedGlobalSkills);
		if (summary) ctx.ui.notify(summary, "info");
	});

	pi.on("input", (event) => {
		for (const name of findExplicitSkillNames(event.text)) explicitSkillsForNextPrompt.add(name);
	});

	pi.on("before_agent_start", (event, ctx) => {
		const profileNames = readEnabledProfiles(ctx.cwd);
		if (profileNames.length === 0) {
			explicitSkillsForNextPrompt = new Set<string>();
			return;
		}

		const allowedGlobalSkills = readAllowedSkills(profileNames) ?? new Set<string>();
		const explicitSkills = explicitSkillsForNextPrompt;
		explicitSkillsForNextPrompt = new Set<string>();

		return {
			systemPrompt: filterSkillsInSystemPrompt(
				event.systemPrompt,
				event.systemPromptOptions,
				allowedGlobalSkills,
				explicitSkills,
			),
		};
	});
}
