syntax enable

set autoread

" ---------------------------------------------------------
" Appearance
" ---------------------------------------------------------
set number relativenumber
set showcmd
set showmatch
set laststatus=2
set title

" ---------------------------------------------------------
" Tab
" ---------------------------------------------------------
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

" ---------------------------------------------------------
" Search
" ---------------------------------------------------------
set ignorecase
set smartcase
set incsearch
set hlsearch
set wrapscan

" ---------------------------------------------------------
" Keymap
" ---------------------------------------------------------
inoremap <silent> jj <ESC>
nnoremap <Esc><Esc> :nohlsearch<CR><ESC>
nmap gT <Plug>AirlineSelectPrevTab
nmap gt <Plug>AirlineSelectNextTab
nmap f <Plug>(easymotion-bd-f2)

" ---------------------------------------------------------
" airline
" ---------------------------------------------------------
" if !exists('g:airline_symbols')
"   let g:airline_symbols = {}
" endif
set laststatus=2
" let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
" let g:airline_symbols.branch = '⭠'
let g:airline_theme = 'luna'

" ---------------------------------------------------------
" Plugins
" ---------------------------------------------------------
call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-surround'
call plug#end()

