function powerline_precmd() {
    PS1="$(powerline-shell --shell zsh $?)"
}

function install_powerline_precmd() {
  for s in ${precmd_functions[@]}; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

# aliases
alias ll='ls -alF'

export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/usr/local/flutter/bin

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi

