format = """
[╭─](fg:#81a1c1)[](#8fbcbb)\
$username$hostname\
[](bg:#5e81ac fg:#8fbcbb)\
$directory\
[](fg:#5e81ac bg:#88c0d0)\
$git_branch\
$git_status\
[](fg:#88c0d0 bg:#4c566a)\
$bun\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$python\
$rust\
[](fg:#4c566a)\
$fill\
[](fg:#5e81ac)\
$time 
[╰](fg:#81a1c1)$character
"""

add_newline = true
command_timeout = 2000

[fill]
symbol = "─"
style = "#5e81ac"

[character]
success_symbol = '[](#81a1c1)'
error_symbol = '[](#bf616a)'
vimcmd_symbol = '[](#81a1c1)'
vimcmd_replace_one_symbol = '[](#81a1c1)'
vimcmd_replace_symbol = '[](#81a1c1)'
vimcmd_visual_symbol = '[](#81a1c1)'

[hostname]
ssh_only = true
format = '[ @$hostname ]($style)'
style = "bg:#8fbcbb"
disabled = false

[username]
show_always = true
style_user = "fg:#37474F bg:#8fbcbb"
style_root = "fg:#d08770 bg:#8fbcbb"
# format = '[ ]($style)'
format = '[󱐋 ]($style)'

[directory]
style = "fg:#ECEFF1 bg:#5e81ac"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[bun]
symbol = ""
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#FAFAFA bg:#4c566a) ($version) ]($style)'

# not working...
[deno]
symbol = ""
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#A5D6A7 bg:#4c566a) ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#42A5F5 bg:#4c566a) $context ]($style) $path'

[git_branch]
symbol = ""
style = "fg:#37474F bg:#88c0d0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold fg:#37474F bg:#88c0d0"
format = '[$all_status $ahead_behind ]($style)'
# up_to_date = '♥'
# untracked = '?'
# stashed = 'S'
# modified = 'M'
# staged = '+'
# renamed = 'R'
# deleted = '-'
ignore_submodules = true

[golang]
symbol = " "
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#BBDEFB bg:#4c566a) ($version) ]($style)'

[java]
symbol = " "
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#F48FB1 bg:#4c566a)($version) ]($style)'

[lua]
symbol = ""
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#90CAF9 bg:#4c566a) ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#81C784 bg:#4c566a) ($version) ]($style)'

[python]
symbol = " "
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#FFF176 bg:#4c566a)${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "fg:#ECEFF4 bg:#4c566a"
format = '[ [$symbol](fg:#F57C00 bg:#4c566a) ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M%P"
style = "fg:#5e81ac"
format = '[ $time ]($style)'
