format = """
[](#9A348E)\
$username$hostname\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#33658A)\
$bun\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$python\
$rust\
[](fg:#33658A bg:#86BBD8)\
$time\
[ ](fg:#86BBD8)
$character 
"""

add_newline = true
command_timeout = 2000

[character]
success_symbol = '[](#86BBD8)'
error_symbol = '[󰚌](#DA627D)'
vimcmd_symbol = '[](#FCA17D)'
vimcmd_replace_one_symbol = '[](#FCA17D)'
vimcmd_replace_symbol = '[](#FCA17D)'
vimcmd_visual_symbol = '[](#FCA17D)'

[hostname]
ssh_only = true
format = '[ @$hostname ]($style)'
style = "bg:#9A348E"
disabled = false

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[ ]($style)'

[directory]
style = "bold fg:#ffffff bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[bun]
symbol = "󰳯 "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bold fg:#ffffff bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bold fg:#ffffff bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold fg:#ffffff bg:#FCA17D"
format = '[$all_status $ahead_behind ]($style)'
up_to_date = '♥'
untracked = 'U'
stashed = 'S'
modified = 'M'
staged = 'A'
renamed = 'R'
deleted = 'D'
ignore_submodules = true

[golang]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#33658A"
format = '[ $symbol${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#33658A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M%P"
style = "fg:#ffffff bg:#86BBD8"
format = '[ ♥ $time ]($style)'
