add_newline = true

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$container\
$shell\
$character"""

[directory]
truncation_length = 8
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_metrics]
disabled = true
