#!/bin/bash

sudo apt update

sudo apt install -y \
  curl \
  git \
  build-essential \
  software-properties-common \
  zip \
  unzip \
  wget

sudo apt install -y \
  libssl-dev zlib1g-dev \
  libbz2-dev libreadline-dev libsqlite3-dev curl \
  libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

sudo add-apt-repository -y ppa:fish-shell/release-3
sudo apt update
sudo apt install -y fish
