#!/bin/bash

sudo apt update

sudo apt install -y \
  curl \
  git \
  build-essential \
  software-properties-common \
  zip \
  unzip \
  wget \
  zlib1g-dev

sudo add-apt-repository -y ppa:fish-shell/release-3
sudo apt update
sudo apt install -y fish
