#!/usr/bin/env bash

sudo apt update

sudo apt install -y \
  curl \
  fuse \
  git \
  build-essential \
  software-properties-common \
  zip \
  uidmap \
  unzip

sudo apt install -y \
  libssl-dev zlib1g-dev \
  libbz2-dev libreadline-dev libsqlite3-dev curl \
  libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
