#!/usr/bin/env bash

if ./bin/installed.sh brew; then
    echo '"brew" is already installed. OK.'
else
    echo '"brew" is NOT installed. Install...'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if test -f /home/linuxbrew/.linuxbrew/bin/brew; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

brew install \
  bat \
  biome \
  bottom \
  cloud-sql-proxy \
  direnv \
  fd \
  ffmpegthumbnailer \
  fish \
  fzf \
  gdu \
  gemini-cli \
  git-delta \
  gh \
  ghq \
  hadolint \
  helix \
  jesseduffield/lazygit/lazygit \
  jesseduffield/lazydocker/lazydocker \
  jj \
  libpq \
  mise \
  neovim \
  nkf \
  nushell \
  onefetch \
  pipenv \
  podman \
  podman-compose \
  poppler \
  pre-commit \
  ruff \
  sqlite \
  starship \
  tig \
  tldr \
  tree-sitter \
  unar \
  wget \
  xh \
  yq \
  zlib \
  zoxide

brew link --force libpq
