#!/bin/bash

VERSION=2.8.1
INSTALL_LOCATION=~/.local/bin

if [ $(uname) == "Darwin" ]; then
  PLATFORM=darwin
else
  PLATFORM=linux
fi

DOWNLOAD_URL=https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v$VERSION/cloud-sql-proxy.$PLATFORM.amd64

wget $DOWNLOAD_URL -O $INSTALL_LOCATION/cloud_sql_proxy
chmod +x $INSTALL_LOCATION/cloud_sql_proxy
