#!/usr/bin/env fish

if test -f ~/.config/fish/functions/fisher.fish
  rm ~/.config/fish/functions/fisher.fish
end
if test -f ~/.config/fish/completions/fisher.fish
  rm ~/.config/fish/completions/fisher.fish
end

cp home/config/fish/fish_plugins /tmp/fish_plugins

curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

for p in (cat /tmp/fish_plugins); fisher install $p; end
